/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1933a7761bc8a5ef2323edac5e9a58f8)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	CMS_ORIGIN: "https://buildscope-blog.com";
	GITHUB_REPOSITORY: "Buildscope365/buildscope-blog";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CMS_ORIGIN" | "GITHUB_REPOSITORY">> {}
}
